object Modules {
	const val app = ":app"
	const val onBoarding = ":on-boarding"
	const val dataMusic = ":music:music-data"
	const val newDataMusic = ":data-music"
	const val coreUi = ":core:ui"
	const val coreModel = ":core:model"
	const val coreCommon = ":core:common"
	const val coreService = ":core:service"
	const val coreData = ":core:data"
	const val coreNavigation = ":core:navigation"
	const val coreDatabase = ":core:database"
	const val featureAlbum = ":feature:album"
	const val featurePlayer = ":feature:player"
	const val featureSong = ":feature:song"
}