object Modules {
	const val app = ":app"
	const val components = ":components"
	const val onBoarding = ":on-boarding"
	const val uiSongs = ":music:ui-songs"
	const val uiAlbums = ":music:ui-albums"
	const val constants = ":constants"
	const val dataMusic = ":music:data-music"
	const val coreUi = ":core-ui"
	const val coreModel = ":core-model"
	const val coreCommon = ":core-common"
	const val coreData = ":core-data"
	const val coreNavigation = ":core-navigation"
	const val coreDatabase = ":core-database"
	const val featurePlayer = ":feature-player"
	const val featureSong = ":feature-song"
}