name: Build Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - name: Write sign info
        if: github.repository == 'Iamlooker/Howl'
        run: |
          if [ ! -z "${{ secrets.KEY_BASE64 }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASS }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEYSTORE_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASS }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEY_BASE64 }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Build Release APK
        run: ./gradlew assembleStaging
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Signed APK
          path: app/build/outputs/apk/staging/*.apk
